


import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.io.*;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author VASUDHA
 */
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTER YOUR CARD DETAILS FOR PAYMENT");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME ON CARD");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CARD NUMBER");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CVV");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 204));
        jButton2.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(494, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(296, 296, 296)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)))
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText(), no = jTextField2.getText(), cvv = jTextField3.getText();
        //System.out.println("Name on card "+ name);
        if(name.equals("") || no.equals("") || cvv.equals(""))
            JOptionPane.showMessageDialog(null, "Please fill in all details");
        else {
            int opt = JOptionPane.showConfirmDialog(null, "Proceed to Pay?");
            if(opt==JOptionPane.YES_OPTION) {
                
                int id = Integer.parseInt(Args[0]), bus_id = Integer.parseInt(Args[3]);
                
                try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sample","root", "Vasu$0308" );
                //Statement stmt = con.createStatement();
               
                /*for(int i=0; i<idx; i++)
                {
                    //String Sql = "UPDATE SEATS SET id = " + id +" WHERE seat_no = " + seats_chosen[i];
                    
                    //System.out.println("id : " + id + " Bus_id: " + bus_id);
                    stmt.executeUpdate(Sql); 
                }*/
                for(int i=0; i<idx; i++) { //filling bus id and seats
                        System.out.print(seats_chosen[i] + " ");
                        PreparedStatement ps2 = con.prepareStatement("insert into SEATS values(?,?,?)");
                        ps2.setInt(1, bus_id);
                        ps2.setInt(2, seats_chosen[i]);
                        ps2.setInt(3, id);
                        
                        ps2.executeUpdate() ;

                    }
              
                }
                catch(Exception e){
                    
                }
                JOptionPane.showMessageDialog(null, "Generating Bill");
                f.dispose();
                
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sample","root", "Vasu$0308" );
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("Select * FROM BUSES WHERE BUS_ID = " + bus_id);
                    rs.next();
                    FileWriter myWriter = new FileWriter("Ticket" + id + "_" + bus_id + "_" + idx + ".txt");
                    
                    myWriter.write("\t\t\t***************************BILL**************************");
                    myWriter.write("\n\nID: " + id + "\nNAME: " + Args[2] + "\nBUS NUMBER: " + bus_id + "\nAC/NONAC: " + rs.getString(2) + "\nSEATS BOOKED: ");
                    for(int i=0; i<idx; i++)
                        myWriter.write(seats_chosen[i] + " ");
                    myWriter.write("\nSOURCE: " + rs.getString(3) + "\nDESTINATION: " + rs.getString(4) + "\nDEPARTURE DATE: " + rs.getString(6));
                    myWriter.write("\nDEPARTURE TIME: " + rs.getString(7) + "\n" + amt.getText() + "\n\n\n\t\t\t***********************PAID*************************");
                    
                    myWriter.close();
                    System.out.println("Successfully wrote to the file.");
                } catch (Exception e) {
                    //System.out.println("An error occurred.");
                    //e.printStackTrace();
                }
                
                
            }

            else if(opt==JOptionPane.NO_OPTION){
            
            }
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: //logout
        String temp[] = {""};
        f.dispose();
        new Login().main(temp);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Args = args;

                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sample","root", "Vasu$0308" );
                    f = new Bill();
                    f.toFront();
                    f.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
                    Color mycolor = new Color(0,0,153);
                    f.getContentPane().setBackground(mycolor);
                    f.setVisible(true);
                    //String[][] sample = new String[][]{{"Apple", "Ball"},{"Cat", "Dog"}, {"Elephant, Fish"} };
                    //String temp = Arrays.deepToString(sample);
                    String temp = args[5];
                    String[] strings = temp.replace("[", "").replace("]", ">").split(", ");
                    List<String> stringList = new ArrayList<>();
                    List<String[]> tempResult = new ArrayList<>();
                    for(String str : strings) {
                        if(str.endsWith(">")) {
                           str = str.substring(0, str.length() - 1);
                           if(str.endsWith(">")) {
                               str = str.substring(0, str.length() - 1);
                           }
                           stringList.add(str);
                           tempResult.add(stringList.toArray(new String[stringList.size()]));
                            stringList = new ArrayList<>();
                        } else {
                            stringList.add(str);
                        }
                    }
                   String[][] originalArray = tempResult.toArray(new String[tempResult.size()][]);
                   int tseats = Integer.parseInt(args[4]), count=1;
                   //seats_chosen[] = new int[20], idx=0; //idx=> actual seats chosen
                   for(int i=0; i<tseats/4; i++) {

                       for(int j=0; j<4; j++) {
                           System.out.print(originalArray[i][j]);
                           if(originalArray[i][j].equals("true"))
                               seats_chosen[idx++]=count;
                           count++;
                       }
                       System.out.println();

                    }
                   //int bus_id = Integer.parseInt(args[3]);
                   
                   //Type here
                   Statement st = con.createStatement();
                   ResultSet rs = st.executeQuery("select PRICE from BUSES where BUS_ID = " + args[3]);
                   rs.next();
                   
                   amt = new JLabel("AMOUNT TO BE PAID: " + (idx * (rs.getInt(1) + 100))); //100 gst
                   amt.setForeground(Color.WHITE);
                   amt.setBounds(530, 100, 300, 50);
                   Font fon = new Font("Cambria",Font.ITALIC,26);
                   amt.setFont(fon);
                   f.add(amt);
                   
                   String s_chosen = Arrays.toString(seats_chosen);
                   seats_booked = new JLabel("SEATS BOOKED: " + s_chosen.replace("[", "").replace("]", "").replace(", 0", "")); 
                   seats_booked.setBounds(550, 150, 300, 50);
                   seats_booked.setForeground(Color.WHITE);
                   seats_booked.setFont(fon);
                   f.add(seats_booked);

                }
                catch(Exception e){
                    
                }
         
        }
        });
    }

    static JFrame f;
    static JLabel amt, seats_booked;
    static String[] Args ; //
    static int[] seats_chosen = new int[20];
    static int idx=0; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
